name: Build Angular 19 App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install  # Gebruik `npm install` i.p.v. `npm ci` als je geen lockfile hebt

      - name: Build Angular app
        run: npm run build

